name: 'Dockerize App'
description: 'Build & publish dockerized apps'
inputs:
  github-token:
    description: 'GH Token'
    required: false
  build:
    description: 'Build docker image'
    required: true
    default: true
  docker-file:
    description: 'Docker file path'
    required: false
  build-path:
    description: 'Build Path'
    required: true
    default: '.'  
  publish:
    description: 'Publish'
    required: false
    default: true
  package-name:
    description: 'Package name'
    required: true
  owner:
    description: 'Organization owner'
    required: true
    default: GETYUGO
  clean:
    description: 'Clean non tagged images'
    required: false
    default: true
  delete-tag:
    description: 'Delete tagged image'
    required: false
    default: false  
  tag:
    description: 'Docker image tag'
    required: true
  build-args:
    description: 'Docker build arguments'
    required: false
  platform:
    description: 'Docker target platform'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
  # post: 'clean.js'
